# Generated by Django 4.1.2 on 2022-11-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_urls', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_urls', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
